### ISSUE TITLE
Include mailto

### ISSUE THREAD

**Issue by cgosorio** [tengucrow/interceptor#1]
First of all, thanks for this useful script, nice work, I had spent several hours trying to fix the problem with gx, and this script did the trick.

Second, and bear in mind that I am a newbie with vim scripts, is this patter correct?
```
"http[^]\"\) ]*"
```
Why do not you need to escape the ']', as you do with '"' and ')'?
And also, why have not you used the same pattern for the other two types of URLs?

And lastly, a suggestion for a small improvement, you could add this
```
  if line==""
      let line=matchstr (line0, "mailto:[^\"\) ]*")
  endif
```
so the script could work also for this type of URLs. I have tried it, and it opens the mail client no problem for URLs like `mailto:cgosorio@ubu.es`.

**Comment by tengucrow** [comment]
Glad my work was useful for someone else :)

Thanks for proposal! Added mail pattern to file.

About `]` in url. As long as I remember its an artifact from old times. 

Long time ago I used to work with [asciidoctor](https://asciidoctor.org) format urls (its markdown language like... emmm... Markdown). It's sometimes URL like:

    search/link:https://ecosia.org[Ecosia]


so, I escaped `]` too 

Its like `)` escaping for markdown links i.e. 

    [Ecosia](https://ecosia.org)

**Comment by cgosorio** [comment]
OK, understood. Thanks for the explanation. But then, should not be the pattern?
```
"http[^\[\"\) ]*"
```
as you want to stop the scanning as soon as the open square bracket appears in the input. Otherwise, the matching string would be `https://ecosia.org[Ecosia`.

**Comment by tengucrow** [comment]
Think it is superfluous now and we can get rid of the difficult heritage of the past :)
